version: '3'

services:

  web:
    container_name: mowgli-web
    image: nginx
    ports:
      - 4005:80
    volumes:
      - ./web:/usr/share/nginx/html:ro
    restart: unless-stopped

  mosquitto:
    container_name: mowgli-mqtt
    hostname: mosquitto
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./config/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped

  roscore:
    container_name: mowgli-roscore
    image: ghcr.io/cedbossneo/mowgli-docker:cedbossneo-amd64
    network_mode: host
    pull_policy: always
    tty: true
    privileged: true
    environment:
      ROS_IP: ${ROS_IP}
    command:
      - /opt/ros/noetic/bin/roscore
    volumes:
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped

  rosserial:
    container_name: mowgli-rosserial
    image: ghcr.io/cedbossneo/mowgli-docker:cedbossneo-amd64
    network_mode: host
    pull_policy: always
    tty: true
    privileged: true
    environment:
      ROS_MASTER_URI: http://${ROS_IP}:11311
      ROS_IP: ${ROS_IP}
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    command:
      - /opt/ros/noetic/bin/rosrun
      - rosserial_server
      - serial_node
      - _port:=/dev/mowgli
      - _baud:=115200
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /dev:/dev
    depends_on:
      - roscore
      - gps-relay
      - mowgli-relay
    restart: unless-stopped

  openmower:
    container_name: mowgli-openmower
    image: ghcr.io/cedbossneo/mowgli-docker:cedbossneo-amd64
    network_mode: host
    pull_policy: always
    tty: true
    privileged: true
    #group_add:   # enable this if you use PiOS
    #  - "104"    # and you want to use a controller
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    environment:
      ROS_MASTER_URI: http://${ROS_IP}:11311
      ROS_IP: ${ROS_IP}
      ROSCONSOLE_CONFIG_FILE: /config/rosconsole.config   # comment this line out to enable more logs
      ROSOUT_DISABLE_FILE_LOGGING: true                   # comment this line out to enable more logs
    tmpfs: /home/ubuntu/.ros/log                          # comment this line out to enable persistent logs
    volumes:
      - ./config/rosconsole.config:/config/rosconsole.config:ro
      - ./config/om:/home/ubuntu/open_mower_ros/src/open_mower/config:ro
      - ./mower_params:/home/ubuntu/mower_params:ro
      - ./params:/home/ubuntu/open_mower_ros/src/open_mower/params:ro
      - ./ros:/home/ubuntu/.ros/
      - /etc/timezone:/etc/timezone:ro
      - /dev:/dev
    depends_on:
      - rosserial
    restart: unless-stopped

  gps-relay:
    image: alpine/socat
    command: "pty,link=/dev/gps,ignoreof,waitslave,group-late=100,user-late=1000,raw,mode=660,echo=0 tcp:${MOWER_IP}:4002"
    privileged: true
    volumes:
    - /dev:/dev
    restart: unless-stopped

  mowgli-relay:
    image: alpine/socat
    command: "pty,link=/dev/mowgli,ignoreof,waitslave,group-late=100,user-late=1000,raw,mode=660,echo=0 tcp:${MOWER_IP}:4001"
    privileged: true
    volumes:
    - /dev:/dev
    restart: unless-stopped
